### ISSUE TITLE
Is this published anywhere?

### ISSUE THREAD

**Issue by p4rty4nimAl** [AlphaMode/fakeconfigtoml#2]
I'm trying to build Create Fabric and can't find where the repository this is in is; the build is failing without it.

This isn't really an issue, but there isn't anywhere else I can find to ask.

**Comment by p4rty4nimAl** [comment]
I've managed to get it to build now.

I first began by cloning this repo, then building it as any normal fabric mod. 
I then put this in `project_folder/.gradle/loom-cache/master-SNAPSHOT/`
This made sure that the build process for Create Fabric was able to find the file, and would then build.
Note: master-SNAPSHOT may be due to my version of loom, and therefore may be different.

**Comment by spectrapulse** [comment]
Could you at least state what you've done?
